FROM alpine:latest
RUN apk --no-cache add tini ca-certificates curl bash rclone openssh tzdata
RUN mkdir -p /tmp
COPY backrest /backrest
RUN /backrest --install-deps-only
RUN mkdir -p /bin && mv /root/.local/share/backrest/* /bin

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/backrest"]